vowel:
 - à
 - â
 - æ
 - é
 - è
 - ê
 - ë
 - î
 - ï
 - ô
 - œ
 - ù
 - û
 - ü
 - ÿ
 - a
 - e
 - u
 - i
 - o
 - ö
 - ä
 - "y"

consonnant:
 - q
 - w
 - r
 - t
 - z
 - p
 - s
 - d
 - f
 - g
 - h
 - j
 - k
 - l
 - x
 - c
 - v
 - n
 - m
 - b
 - ι
 - F
 - υ
 - ç

exeption:
  gυ: C
  gu: C
  ue: V
  eu: V
  qυ: C
  ai: V
  ay: V
  oeil: V
  au: V
  Fèel: V
  qu: C
  ou: V
  ch: C
  oeul: V
  on: V
  #ion: V
  gn: C
  ei: V
  pr: C
  oi: V
  ui: V
  oy: V
  oe: V
  ié: V
  que: V
  ent: V
  es: V
  vient: V
  viënt: V
  tient: V
  tiënt: V
  iau: V
  eau: V
  eaz: V

ier:
  - vr
  - rg
  - ch
  - tr
  - rr
  - ll
  - pp
  - lc
  - mc
  - sc
  - gn
  - ss
  - sn
  - st
  - nd
  - nb
  - nc
  - nf
  - nh
  - ng
  - nj
  - nk
  - nl
  - nm
  - np
  - nq
  - nr
  - ns
  - nt
  - nv
  - nw
  - nx
  - nz
  - md
  - mb
  - mc
  - mf
  - mh
  - mg
  - mj
  - mk
  - ml
  - mm
  - mp
  - mq
  - mr
  - ms
  - mt
  - mv
  - mw
  - mx
  - mz
  - rt
  - rc
  - h
  - l
