proesce:
  - pro
  - es
  - ce

kaerlïun:
  - kaer
  - lï
  - un

proescë:
  - pro
  - es
  - cë

puir:
  - pu
  - ir

prιer:
  - prι
  - er

marιer:
  - ma
  - rι
  - er

crestιen:
  - cres
  - tι
  - en

chrestien:
  - chres
  - tι
  - en

crestιens:
  - cres
  - tι
  - ens

crestιens:
  - chres
  - tι
  - ens

crestιent:
  - chres
  - tι
  - ent

crestιenté:
  - chres
  - tι
  - en
  - té

bués:
  - bués

fremιanz:
  - fre
  - mι
  - anz

alions:
  - a
  - li
  - ons

curιos:
  - cu
  - ri
  - os

alié:
  - al
  - i
  - é

heiaumë:
  - heiau
  - më

heiaume:
  - heiau
  - me

solιez:
  - so
  - li
  - ez

poez:
  - po
  - ez

poir:
  - po
  - ir

escιence:
  - es
  - ci
  - en
  - ce

descιence:
  - des
  - ci
  - en
  - ce

escιencë:
  - es
  - ci
  - en
  - cë

descιencë:
  - des
  - ci
  - en
  - cë

espoentable:
  - es
  - po
  - en
  - ta
  - ble

espoentablë:
  - es
  - po
  - en
  - ta
  - blë

espoentables:
  - es
  - po
  - en
  - ta
  - bles

espoentablës:
  - es
  - po
  - en
  - ta
  - blës

queu:
  - queu

roem:
  - ro
  - em

siecle:
  - siè
  - cle

sieclë:
  - siè
  - clë

beiaus:
  - beiaus

biaté:
  - bia
  - té

espoentable:
  - es
  - po
  - en
  - ta
  - ble

espoentablë:
  - es
  - po
  - en
  - ta
  - blë

espoentables:
  - es
  - po
  - en
  - ta
  - bles

envioent:
  - en
  - vi
  - o
  - ent

vιengent:
  - vi
  - en
  - gent

fieu:
  - fieu

lieu:
  - lieu

lius:
  - lius

scιence:
  - scι
  - en
  - ce

scιencë:
  - scι
  - en
  - cë

piesa:
  - pie
  - sa

fiere:
  - fie
  - re

fierë:
  - fie
  - rë

fier:
  - fier

dieu:
  - dieu

dius:
  - dius

dios:
  - dios

cier:
  - cier

sieut:
  - sieut

loer:
  - lo
  - er

lués:
  - lués

druerie:
  - dru
  - e
  - ri
  - e

druerië:
  - dru
  - e
  - ri
  - ë

tablier:
  - ta
  - blier

biut:
  - biut

orιant:
  - o
  - ri
  - ant

orιent:
  - o
  - ri
  - ent

lιon:
  - lι
  - "on"

leon:
  - le
  - "on"

conquere:
  - con
  - que
  - rë

quanque:
  - quan
  - quë

quancque:
  - quanc
  - quë

gutte:
  - gut
  - te

guttë:
  - gut
  - të

avoer:
  - a
  - vo
  - er

vueil:
  - veuil

vueille:
  - veuil
  - 

vueillë:
  - veuil
  - lë

lui:
  - lui

luy:
  - luy

chieri:
  - chie
  - ri

noer:
  - "no"
  - er

tresnoer:
  - tres
  - "no"
  - er

desnoer:
  - des
  - "no"
  - er

tyolet:
  - ty
  - o
  - let

tιolet:
  - tι
  - o
  - let

liuës:
  - li
  - ues

leaumënt:
  - le
  - au
  - ment

triës:
  - triës

eriaans:
  - e
  - ria
  - ans

fius:
  - fιus

griu:
  - grιu

piez:
  - pιez

vns:
  - uns

poelet:
  - po
  - e
  - let

ués:
  - ués

leaus:
  - le
  - aus