proesce:
  - pro
  - es
  - ce

kaerlïun:
  - kaer
  - lï
  - un

poeiënt:
  - poe
  - ιënt

mesprisiun:
  - mes
  - pri
  - siun

proescë:
  - pro
  - es
  - cë

proechë:
  - pro
  - es
  - chë

#roland
muer:
  - mu
  - er

muers:
  - mu
  - ers

muez:
  - mu
  - ez

gabriel:
  - ga
  - bri
  - el

gabrιel:
  - ga
  - bri
  - el

luer:
  - lu
  - er

chrestïen:
  - chres
  - tï
  - en

chrestïens:
  - chres
  - tï
  - ens

chrestιentet:
  - chres
  - tï
  - en
  - tet

leun:
  - le
  - un

leuns:
  - le
  - uns

aluee:
  - a
  - lu
  - e
  - e

otrιet:
  - o
  - tri
  - et

saluez:
  - sa
  - lu
  - ez

vιolees:
  - vi
  - o
  - le
  - es

juer:
  - ju
  - er

poent:
  - po
  - ent

quιement:
  - qui
  - e
  - ment

proecces:
  - pro
  - ec
  - ces

capuel:
  - ca
  - pu
  - el

otrιer:
  - o
  - tri
  - er

danιel:
  - da
  - ni
  - el

cherιant:
  - che
  - ri
  - ant

samuel:
  - sa
  - mu
  - el

occιan:
  - oc
  - ci
  - an

ocιant:
  - o
  - ci
  - ant

quιad:
  - qui
  - ad

marcilië:
  - mar
  - ci
  - lιë

marcilie:
  - mar
  - ci
  - lιe

marsilië:
  - mar
  - si
  - lιë

marsilie:
  - mar
  - si
  - lιe

marsillïes:
  - mar
  - sil
  - lιes
#Ici, on a un problème : pour une raison inconnue, le PAM double le "l" de Marsilies (l. 89, roland) et dote le "i" d'un tréma... Le placer ici ne corrige le phénomène qu'en surface.

basilië:
  - ba
  - si
  - lιë

basilie:
  - ba
  - si
  - lιe

basillïes:
  - ba
  - si
  - lιes
#idem _marsillïes_.

iloυec:
  - i
  - loec

fiu:
  - fiu

giu:
  - giu

liez:
  - lιez

milie:
  - mi
  - lie

milië:
  - mi
  - lië

espiez:
  - es
  - piez

avisiun:
  - a
  - vi
  - siun

munies:
  - mu
  - nιes

canonies:
  - ca
  - \no
  - nιes
#Pour Enzo. L'échappement avec l'antislash ne marche pas, parce qu'il comprend le \ comme un vrai caractère. Le v. impliqué est dans Roland, numéro 2954.

bramidonie:
  - bra
  - mi
  - do
  - nιe

bramidonië:
  - bra
  - mi
  - do
  - nιë

muriuns:
  - mu
  - riuns

#end_roland

#lιez:
#  - li
#  - ez
#À rétablir hors Roland.

proeche:
  - pro
  - es
  - che

porquei:
  - por
  - quei

conscιence:
  - con
  - sci
  - en
  - ce

conscιencë:
  - con
  - sci
  - en
  - cë

efforcieement:
  - ef
  - for
  - cie
  - e
  - ment

especialement:
  - es
  - pe
  - cia
  - le
  - ment

efforcieemënt:
  - ef
  - for
  - cie
  - e
  - ment

precιeus:
  - pre
  - ci
  - eus

precιeuse:
  - pre
  - ci
  - eu
  - se

precιeusë:
 - pre
 - ci
 - eu
 - së

precιeusës:
 - pre
 - ci
 - eu
 - sës

voailënt:
  - voai
  - lënt

lié:
  - li
  - é

defιer:
  - de
  - fi
  - er

delιee:
  - de
  - li
  - e
  - e

soue:
  - sou
  - e

legιerement:
  - le
  - gi
  - e
  - re
  - ment

contien:
  - con
  - tien

delιeë:
  - de
  - li
  - e
  - ë

sourιant:
  - sou
  - ri
  - ant

deligeament:
  - de
  - li
  - gea
  - ment

purquei:
  - pur
  - quei

iës:
  - iës

puir:
  - pu
  - ir

prιer:
  - prι
  - er

marιer:
  - ma
  - rι
  - er

crestιen:
  - cres
  - tι
  - en

chrestien:
  - chres
  - tι
  - en

crestιens:
  - cres
  - tι
  - ens

merrïen:
  - mer
  - rien

crestιens:
  - chres
  - tι
  - ens

parroissιens:
  - par
  - roi
  - si
  - ens

crestιent:
  - chres
  - tι
  - ent

seintuere:
  - sein
  - tu
  - er
  - e

seintuerë:
  - sein
  - tu
  - er
  - ë

seintuerës:
  - sein
  - tu
  - er
  - ës

cretïens:
  - cre
  - ti
  - ens

cretïen:
  - cre
  - ti
  - en

crestιenté:
  - chres
  - tι
  - en
  - té

einseint:
  - eins
  - se
  - int

deum:
  - de
  - um

bués:
  - bués

fremιanz:
  - fre
  - mι
  - anz

alions:
  - a
  - li
  - ons

curιos:
  - cu
  - ri
  - os

alié:
  - al
  - i
  - é

rιans:
  - ri
  - ans

rιant:
  - ri
  - ant

puës:
  - pues

pues:
  - pues

heiaumë:
  - heiau
  - më

heiaume:
  - heiau
  - me

solιez:
  - so
  - li
  - ez

poez:
  - po
  - ez

quei:
  - quei

ottrιee:
  - ot
  - tri
  - e
  - e

entreamerënt:
  - en
  - trea
  - me
  - rënt

ottrιëe:
  - ot
  - tri
  - e
  - Ë

poir:
  - po
  - ir

poer:
  - po
  - er

escιence:
  - es
  - ci
  - en
  - ce

descιence:
  - des
  - ci
  - en
  - ce

escιencë:
  - es
  - ci
  - en
  - cë

descιencë:
  - des
  - ci
  - en
  - cë

espoentable:
  - es
  - po
  - en
  - ta
  - ble

espoentablë:
  - es
  - po
  - en
  - ta
  - blë

espoentables:
  - es
  - po
  - en
  - ta
  - bles

espoentablës:
  - es
  - po
  - en
  - ta
  - blës

queu:
  - queu

roem:
  - ro
  - em

siecle:
  - siè
  - cle

sieclë:
  - siè
  - clë

beiaus:
  - beiaus

biaté:
  - bia
  - té

espoentable:
  - es
  - po
  - en
  - ta
  - ble

espoentablë:
  - es
  - po
  - en
  - ta
  - blë

espoentables:
  - es
  - po
  - en
  - ta
  - bles

bercier:
  - ber
  - cier

envioent:
  - en
  - vi
  - o
  - ent

vιengent:
  - vi
  - en
  - gent

fieu:
  - fieu

lieu:
  - lieu

lius:
  - lius

scιence:
  - scι
  - en
  - ce

scιencë:
  - scι
  - en
  - cë

piesa:
  - pie
  - sa

fiere:
  - fie
  - re

siut:
  - siut

fierë:
  - fie
  - rë

graalënt:
  - gra
  - a
  - lënt

fier:
  - fier

esmué:
  - es
  - mué

dieu:
  - dieu

dius:
  - dius

diu:
  - diu

coeur:
  - coeur

coeurs:
  - coeurs

poeut:
  - poeut

iloeuc:
  - i
  - iloeuc

dios:
  - dios

cier:
  - cier

sieut:
  - sieut

loer:
  - lo
  - er

lués:
  - lués

druerie:
  - dru
  - e
  - ri
  - e

drueries:
  - dru
  - e
  - ri
  - es

avoez:
  - a
  - vo
  - ez

oez:
  - o
  - ez

afichιement:
  - a
  - fi
  - chi
  - e
  - ment

druerië:
  - dru
  - e
  - ri
  - ë

rius:
  - rius

biute:
  - biu
  - te

mathius:
  - ma
  - thius

ceo:
  - ceo

luës:
  - lues

beateit:
  - bea
  - teit

jeo:
  - jeo

süer:
  - suer

tablier:
  - ta
  - blier

terrιen:
  - ter
  - ri
  - en

terrιens:
  - ter
  - ri
  - ens

terrιennë:
  - ter
  - ri
  - en
  - në

juscιenne:
  - jus
  - ci
  - en
  - ne

juscιennë:
  - jus
  - ci
  - en
  - në

juscιennës:
  - jus
  - ci
  - en
  - nës

obedιence:
  - o
  - be
  - di
  - en
  - ce

especιal:
  - es
  - pe
  - ci
  - al

obedιencë:
  - o
  - be
  - di
  - en
  - cë

terrιenne:
  - ter
  - ri
  - en
  - ne

terrιennës:
  - ter
  - ri
  - en
  - nës

biut:
  - biut

orιant:
  - o
  - ri
  - ant

orιent:
  - o
  - ri
  - ent

afιas:
  - a
  - fi
  - as

esquële:
  - es
  - qu
  - ë
  - le

esquëlë:
  - es
  - qu
  - ë
  - lë

lιon:
  - lι
  - "on"

leon:
  - le
  - "on"

conquere:
  - con
  - que
  - rë

quanque:
  - quan
  - quë

quancque:
  - quanc
  - quë

gutte:
  - gut
  - te

guttë:
  - gut
  - të

avoer:
  - a
  - vo
  - er

vueil:
  - veuil

vueille:
  - veuil
  -

vueillë:
  - veuil
  - lë

lui:
  - lui

luy:
  - luy

chieri:
  - chie
  - ri

noer:
  - "no"
  - er

tresnoer:
  - tres
  - "no"
  - er

desnoer:
  - des
  - "no"
  - er

tyolet:
  - ty
  - o
  - let

tιolet:
  - tι
  - o
  - let

liu:
  - liu

atient:
  - a
  - tient

füer:
  - fuer

cüer:
  - cuer

süer:
  - suer

riestis:
  - rιest
  - tis

hardιeche:
  - ar
  - di
  - e
  - che

recheürent:
  - re
  - cheu
  - rent

receürent:
  - re
  - ceu
  - rent

vuolt:
  - vuolt

vuolënt:
  - vuo
  - lënt

hardιechë:
  - ar
  - di
  - e
  - chë

ardιeche:
  - ar
  - di
  - e
  - che

ardιechë:
  - ar
  - di
  - e
  - chë

oës:
  - oes

liuës:
  - li
  - ues

leaumënt:
  - le
  - au
  - ment

triës:
  - triës

eriaans:
  - e
  - ria
  - ans

fius:
  - fιus

griu:
  - grιu

piez:
  - pιez

vns:
  - uns

poelet:
  - po
  - e
  - let

ués:
  - ués

leaus:
  - le
  - aus
