list:
 - et
 - que
 - et
 - qu
 - ou
 - ne
 - e
 - quant
 - car
 - se
 - comme
 - mais
 - que
 - e
 - quant
 - mais
 - s
 - ke
 - car
 - com
 - cum
 - qu
 - se
 - ne
 - mes
 - mes
 - qe
 - come
 - con
 - s
 - u
 - c
 - k
 - qu’
 - kar
 - ou
 - cant
 - cume
 - ke
 - kar
 - qant
 - quar
 - n
 - cum
 - quar
 - conme
 - comme
 - maiz
 - et
 - n
 - com
 - c
 - si
 - u
 - k
 - cume
 - qant
 - soit
 - sicume
 - quer
 - ny
 - con
 - q
 - sicom
 - maiz
 - quand
 - si
 - ni
 - s’
 - cant
 - come
 - puisque
 - o
 - sicome
 - sicomme
 - mez
 - o
 - conme
 - desque
 - q
 - dunc
 - qar
 - sy
 - mez
 - meis
 - ques
 - meis
 - puisqu
 - qar
 - cumme
 - quer
 - desque
 - sicum
 - sicume
 - char
 - cun
 - ce
 - puisque
 - vel
 - qu
 - quë
 - quë
 - usque
 - ker
 - quand
 - tresque
 - qe
 - siques
 - queque
 - queque
 - ker
 - në
 - nes
 - puisqu
 - sed
 - c’
 - quel
 - sicum
 - në
 - qel
 - quan
 - quel
 - sel
 - s’
 - cu
 - cunme
 - cy
 - kel
 - quae
 - qued
 - quequ
 - cumme
 - desqu
 - or
 - së
 - usque
 - mays
 - mé
 - quan
 - sem
 - sem
 - ses
 - sil
 - soit
 - sy
 - tanque
 #- commanderent
 - coume
 - cumë
 #- dementieres
 - dont
 - net
 - n’
 - qe
 - quandius
 - quet
 - sel
 - set
 - usque
 - ainz
 - car
 - che
 - cum
 - desqu
 - dunc
 - en
 - entreusque
 - jusque
 - nem
 - quanque
 - quare
 - ques
 - qui
 - qu’
 - sis
 - a
 - ains
 - ainz
 - altre
 - ch
 - commenc
 - cumë
 - d
 - des
 - dom
 - dontre
 - dunches
 - el
 - entroeusque
 #- est
 - jusqu
 - kel
 - mai
 - mé
 - ne
 - neïs
 - ny
 - or
 - puis
 - qos
 - qua
 - quanc
 - quantil
 - quaunt
 - qui
 - se
 - ses
 - set
 - sicom
 - sicome
 - sicomme
 - tanqu
 - tresq
 - tresqu
 - tresqu
