list:
 - ce
 - cil
 - cil
 - ceo
 - ço
 - c
 - ce
 - celui
 - cele
 - ço
 - chou
 - c
 - cels
 - che
 - ceulx
 - ceus
 - ces
 - celi
 - cist
 - cele
 - chil
 - cestui
 - ceo
 - chiaus
 - ceste
 - iceo
 - celes
 - cez
 - cel
 - celui
 - icil
 - ice
 - iço
 - cist
 - çaus
 - icil
 - celuy
 - çou
 - ch
 - icels
 - chis
 - ç
 - çals
 - cecy
 - cels
 - chiax
 - ciaus
 - cela
 - ceste
 - celi
 - cho
 - ceaz
 - ceulz
 - chelui
 - iceo
 - celle
 - cesti
 - cio
 - ice
 - cel
 - ceuls
 - ceuz
 - celei
 - celes
 - iço
 - ceaux
 - celz
 - ciax
 - cellui
 - ces
 - cest
 - che
 - o
 - ycelle
 - zo
 - iceste
 - icist
 - se
 - celles
 - celoi
 - ceulx
 - chil
 - icels
 - iciz
 - ycelles
 - yceulx
 - cestui
 - cestuy
 - ça
 - ceaus
 - celle
 - cio
 - iceaz
 - icel
 - icele
 - iceste
 - icez
 - icist
 - ycellui
 - ce
 - celluy
 - cestes
 - cez
 - cheli
 - çoe
 - icele
 - iceles
 - icelle
 - icellui
 - se
 - çals
 - çaüs
 - cella
 - celz
 - cestes
 - ceux
 - cheles
 - çoe
 - çol
 - icel
 - icelui
 - icés
 - icest
 - icest
 - iceulx
 - sa
 - aquel
 - ç
 - çal
 - çaus
 - çax
 - cë
 - ceaus
 - ceci
 - cel
 - cela
 - celë
 - celié
 - cella
 - celoi
 - celuy
 - cen
 - cen
 - cés
 - cest
 - cesti
 - cestuy
 - cetui
 - ceu
 - ceuls
 - ceus
 - ceüs
 - cex
 - ch
 - cha
 - chaus
 - chele
 - chelu
 - chelui
 - cheux
 - chis
 - chist
 - chist
 - chou
 - ci
 - cials
 - ciauz
 - ciel
 - ciel
 - cieus
 - cils
 - cis
 - cis
 - cix
 - ciz
 - co
 - çols
 - çué
 - cyl
 - icelles
 - icelluy
 - icelui
 - ices
 - icetui
 - iceus
 - ichist
 - icho
 - iciz
 - içoe
 - içoe
 - ital
 #- oïl
 - sil
 - yce
 - yceu
