list:
 - de
 - en
 - a
 - par
 - d
 - pour
 - à
 - des
 - au
 - du
 - por
 - de
 - sur
 - a
 - del
 - en
 - sans
 - ou
 - par
 - devant
 - as
 - an
 - pur
 - dou
 - dudit
 - al
 - el
 - entre
 - sanz
 - contre
 - avec
 - vers
 - aux
 - es
 - pour
 - por
 - jusques
 - sor
 - après
 - devers
 - avecques
 - d
 - o
 - od
 - per
 - pur
 - aprés
 - audit
 - selonc
 - sus
 - au
 - des
 - aus
 - oudit
 - selon
 - puis
 - environ
 - ès
 - seur
 - dedens
 - senz
 - encontre
 - de
 - fors
 - del
 - envers
 - d’
 - ad
 - soubz
 - parmi
 - sur
 - jusqu
 - desoz
 - az
 - el
 - depuis
 - in
 - al
 - avoec
 - duquel
 - ouquel
 - avant
 - apres
 #- vers
 - du
 #- excepté
 #- od
 #- as
 - dessus
 - entre
 - devant
 - entour
 - dedans
 - sans
 - dedenz
 - desdiz
 - aprez
 - dudict
 #- encuntre
 - em
 - auquel
 - aprés
 - o
 - hors
 - oultre
 - sor
 - u
 - dès
 - entor
 - desus
 - sens
 - parmy
 #- an
 - outre
 - lez
 - dou
 - sauf
 - entr
 - dez
 #- atout
 - desor
 - solunc
 - sinon
 - delez
 - audict
 - sanz
 - dessoubz
 - aveuc
 - es
 - ausdiz
 #- durant
 - en
 - enmi
 - fors
 #- desdites
 - après
 - soz
 - contre
 - antre
 - sulunc
 - avec
 - souz
 - in
 - suz
 - jesque
 - davant
 - aveuques
 - ou
 - sous
 - ens
 - dedanz
 - endroit
 - avoc
 - auoc
 - paravant
 - après
 - dessous
 - san
 - jusque
 - senz
 - nonobstant
 - envers
 - solonc
 - sulunc
 - auquel
 - aveques
 - desquelles
 - desuz
 - aprez
 - dedenz
 #- chiés
 - ultre
 - parmi
 - aux
 - dedens
 - lez
 - cuntre
 - desouz
 - ancontre
 - sus
 - desquelx
 - entur
 - apres
 - puis
 - defors
 - desur
 - deuant
 - in
 - avecques
 - devers
 - desque
 - près
 - encontre
 - seur
 - contreval
 - ez
 - maugré
 - dès
 - do
 - d
 - selonc
 - ainz
 - emmi
 #- esdites
 - cuntre
 - emprés
 - ver
 - aval
 - avecq
 - antr
 - esquelles
 - for
 - ot
 - per
 - derriere
 - deseur
 - desus
 - ouquel
 - suz
 - des
 - ovec
 - du
 - ent
 - avoec
 - ad
 - envyron
 - seinz
 - antor
 - aus
 - ab
 - deçà
 - desdis
 - jusqu
 - juste
 - parmei
 - apréz
 - enmi
 - atot
 - derrière
 - desur
 - encuntre
 - dessuz
 - ovoec
 - pendant
 - encoste
 - oltre
 - ovesque
 - vecy
 - ouquel
 - chez
 - chiez
 - dehors
 - dela
 - esdiz
 - jasoit
 - juques
 - pro
 - tresqu
 - desous
 - desoz
 - dans
 - deléz
 #- estre
 - ové
 - pour
 - aulx
 - delez
 - desor
 - durant
 - entr
 - contra
 - dé
 - deça
 - desuz
 - dusques
 - pres
 #- estre
 - les
 - ou
 - pardevers
 - ains
 - endreit
 - entor
 - ove
 - selon
 - vecy
 - depuis
 - enprés
 - environ
 - eu
 - ioskes
 - jouste
 - anvers
 - dalés
 - emprez
 - inter
 - maugré
 - ov
 - selunc
 - tresque
 - anviron
 - ciés
 # - dejuste
 - delés
 - dés
 - dessoure
 - dusc
 - sens
 - dejoste
 - desseur
 - enz
 - jusque
 - soz
 - anprés
 - ansanble
 - anz
 - aprof
 - dels
 - desquels
 - duquel
 - em
 - emprés
 - enz
 - sour
 - als
 - antre
 - az
 - derrier
 - entur
 - selunc
 - sen
 - souz
 - u
 - avoeques
 - desque
 - deuenz
 - esquelx
 - joste
 - juste
 - outre
 - dedans
 - jucques
 - post
 - ahier
 - ançois
 - avuec
 - chiés
 - deci
 - defors
 - dejouste
 - deseur
 - durans
 - queles
 - queus
 - ainçois
 - arriere
 - avers
 #- contremont
 - deseure
 - desqu
 - enprés
 - enpur
 - enter
 - soux
 - tresqu
 - ultre
 - am
 - anmi
 - apréz
 - audit
 - auxquelles
 - del
 - desquelles
 - er
 - léz
 - nonobstant
 - saunz
 - sulum
 - tres
 - androit
 - aval
 - avant
 - avecque
 - dedanz
 # - dejuste
 - deleiz
 - deriere
 - dés
 - endroit
 - entresqu
 - solunc
 - amprés
 - ariere
 - atot
 - aveuc
 - dedevant
 - derriers
 - desoubz
 - desqueus
 - e
 - einz
 - einz
 - entresqu
 - envirun
 - jusq
 - ob
 - oultre
 - ovesques
 - sos
 - sulum
 - vela
 - ainz
 - amont
 - ancontre
 - ansemant
 - aprof
 - ausdictes
 - derere
 - desox
 - desquelx
 - detrés
 - dez
 #- dit
 - dusqu
 - d’
 - ell
 - els
 - encontr
 - endreit
 - ensenble
 - jesqu
 - jouste
 - mi
 - oveques
 - ovoc
 - san
 - seure
 - tres
 - apriés
 - audict
 - auquel
 - avan
 - avesques
 - desdicts
 - desos
 - desouz
 - duqu
 - enpur
 - entour
 - jesqu
 - jusques
 - jusqu’
 - léz
 - lonc
 - lunc
 - maulgré
 - par
 - pos
 - soantre
 - solonc
 - sonc
 - sulun
 - .ii.
 - amunt
 - anjusque
 - anpor
 - anson
 - antr
 - anz
 - aproef
 - atout
 - contr
 - contremunt
 - contreval
 - dalés
 - dedesuz
 - dedevant
 - deléz
 - dens
 - derrieres
 - desi
 - desous
 - dessore
 - devens
 - emmi
 - enchiés
 - enpor
 - ensur
 - entresque
 - enviers
 - ez
 - jesque
 - josqu
 - josqu
 - josque
 - meis
 - oveque
 - ovoc
 - parmié
 - pus
 - sau
 - seinz
 - so
 - soubz
 - sous
 - tanque
 - triés
 - al
 - amont
 - amunt
 - ancoste
 - anprés
 - anson
 - apriés
 - aulx
 - auprès
 - auqes
 - ausdicts
 - avé
 - avoc
 - avuec
 - ciés
 - contra
 - dans
 - davant
 - dejouste
 - derriers
 - dudit
 - dusqu
 - enmié
 - ens
 - ensobre
 - entrë
 - entres
 - entresque
 - entr’
 - esquelles
 - eu
 #- evesque (removed for _roland_).
 - for
 - forsque
 - hors
 - ies
 - jasoit
 - lonc
 - maleoit
 - oël
 - oltre
 - os
 - pa
 - par-deçà
 - parmei
 - parmié
 - part
 - pus
 - sinoun
 - so
 - sobre
 - sot
 - su
 - super
 - surs
 - tandis
 - travers
 - tresque
 - triés
 - triez
 #- ·ssubr'
 - amprés
 - andreit
 - androit
 - anjusqu
 - anpur
 - ansenble
 - ansoiz
 - antor
 - au
 - audictz
 - auoc
 - auxquelles
 - auxquels
 - avé
 - avers
 - avesques
 - aveuques
 - avoecques
 - avoques
 - ax
 - ça
 - chiez
 - chiéz
 - ciez
 - con
 - cuntr
 - davan
 - deci
 - dedavant
 - dedeins
 - dedeins
 - dedesuz
 - dejoste
 - dela
 - delés
 - depuis
 - derrière
 - desaux
 - desou
 - desoubz
 - desouthe
 - desquels
 - desriers
 - dessoubz
 - deuant
 - deviers
 - dusque
 - e
 - eg
 - einçois
 - ell
 - empur
 - encoste
 - enjusqu
 - enmié
 - enmy
 - ensobre
 - ensor
 - ensur
 - ensus
 - ensuz
 - entesqu
 - entra
 - entre
 - entrequ
 - envirun
 - envyron
 - excepté
 - gesqu
 - granz
 - incontra
 - iusqu
 - josque
 - joste
 - jusche
 - jusq
 - jusquë
 - laz
 - ové
 - ovec
 - ovesque
 - ovocques
 - ovoeques
 - parentre
 - pendant
 - petit
 - por
 - porr
 - porr
 - post
 - prez
 - pro
 - qu
 - sauf
 - saunz
 - secund
 - selonc
 - sen
 - senun
 - senz
 - soantre
 - sobl
 - sobr
 - sobrae
 - sobre
 - solounc
 - sour
 - suentre
 - sulung
 - tot
 - tresc
 - trestoz
 - trusq
 - ver
 - vier
