list:
 - la
 - le
 - li
 - l
 - les
 - sa
 - son
 - un
 - ses
 - li
 - une
 - la
 - mon
 - vostre
 - ma
 - sun
 - tel
 - lor
 - cest
 - ceste
 - le
 - leur
 - mes
 - l
 - les
 - lur
 - nul
 - s
 - cele
 - toz
 - .i.
 - cel
 - nule
 - ces
 - lo
 - uns
 - tot
 - nostre
 - quel
 - tous
 - ce
 - tote
 - autre
 - tout
 - nostre
 - se
 - ung
 - ta
 - tuit
 - cil
 - toutes
 - voz
 - un
 - toute
 - tut
 - tuz
 - ton
 - m
 - une
 - maint
 - si
 - totes
 - cez
 - ses
 - trois
 - tute
 - nus
 - lez
 - leurs
 - mun
 - sa
 - .ii.
 - deux
 - cist
 - noz
 - mon
 - sen
 - autres
 - mainte
 - ceste
 - tes
 - son
 - touz
 - uns
 - ches
 - ledit
 - ma
 - tele
 - quatre
 - dous
 - mil
 - sis
 - vostre
 - icel
 - vos
 - ledict
 - tuit
 - chascun
 - plusieurs
 - deus
 - altre
 - cent
 - me
 - mi
 - sun
 - aucune
 - tex
 - icele
 - .i.
 - maintes
 - chele
 - nos
 - celle
 - tutes
 - cil
 - quelque
 - treis
 - tut
 - mes
 - unes
 - cele
 - tel
 - toz
 - ycellui
 - cist
 - set
 - tun
 - cel
 - mis
 - lor
 - cens
 - cest
 - chu
 - dis
 - quel
 - .v.
 - ladite
 - nuls
 - des
 - lu
 - nulle
 - tote
 - dui
 - .c.
 - .ii.
 - plusurs
 - .iii.
 - icest
 - aucun
 - quele
 - .iiii.
 - tels
 - maint
 - tot
 - tuz
 - vo
 - .j.
 - cenz
 - lur
 - toutz
 - trestot
 - trestoz
 - tute
 - ces
 - chel
 - vint
 - cest
 - cinc
 - cinq
 - cascun
 - mainz
 - men
 - s
 - sez
 - si
 - t
 - six
 - .iii.
 - .vii.
 - .xii.
 - mille
 - quinze
 - .c.
 - .xx.
 - ce
 - milie
 - quex
 - sis
 - chascune
 - ciz
 - trente
 - trestuit
 - trois
 - .xx.
 - cellui
 - itel
 - lour
 - quarante
 - telle
 - lequel
 - no
 - plusors
 - .iiij.
 - .x.
 - iceste
 - m
 - mile
 - sondit
 - tant
 - tantes
 - .iiii.
 - .v.c.
 - chascun
 - ledict
 - moun
 - nus
 - quatre
 - tes
 - teus
 - totes
 - .lx.
 - .vi.
 - .xxx.
 - aucuns
 - aultre
 - autre
 - cel
 - dous
 - el
 - tante
 - .xv.
 - celui
 - cinquante
 - nostres
 - nul
 - nule
 - tex
 - trestuz
 - cent
 - chest
 - ciel
 - icelle
 - un
 - .ij.
 - .vii.
 - .xv.
 - alcune
 - altres
 - aucunes
 - aultres
 - chis
 - diverses
 - iceste
 - icil
 - laquelle
 - lo
 - pluseurs
 - tous
 - tout
 - toute
 - treis
 - trestut
 - trestute
 - .c.m.
 - cestui
 - cis
 - dix
 - dui
 - ladicte
 - mis
 - quels
 - tanz
 - tos
 - trestote
 - uit
 - cheste
 - douz
 - huit
 - queile
 - queus
 - toutes
 - trestut
 - .x.
 - icele
 - ii
 - sos
 - .v.
 - autel
 - cez
 - chil
 - duze
 - i
 - icil
 - mil
 - plusurs
 - quei
 - ta
 - tanz
 - trestout
 - trestoz
 - .viii.
 - .xxx.
 - anbedeus
 - chaün
 - lu
 - mainte
 - mun
 - que
 - sept
 - set
 - sue
 - tis
 - troi
 - tutes
 - unne
 - vingt
 - xx
 - ycelle
 - .iij.
 - .lx.
 - altre
 - ambes
 - autrez
 - dis
 - icel
 - lé
 - mi
 - pluisors
 - quelques
 - tant
 - ten
 - ti
 - touz
 - ung
 - voz
 - .ix.
 - .xii.
 - chens
 - chent
 - las
 - lesdictz
 - maintes
 - meint
 - nostres
 - queil
 - quelle
 - soisante
 - telles
 - telz
 - viij
 - .xl.
 - alcun
 - celle
 - chelui
 - chescun
 - deus
 - douze
 - iiij
 - lequel
 - lors
 - nulles
 - qel
 - quanz
 - quelz
 - quiex
 - sum
 - te
 - ton
 - trestuit
 - un
 - vj
 - x
 - .xiiii.
 - aucune
 - cascuns
 - chaün
 - chinquante
 - chus
 - doi
 - es
 - icelle
 - icellui
 - icelui
 - laquele
 - lesdiz
 - lez
 - los
 - meinte
 - moun
 - noz
 - nuef
 - nules
 - quarante
 - queiz
 - quiex
 - tantes
 - trestotes
 - trestuz
 - tun
 - vostres
 - alcunes
 - andui
 - aultre
 - c.
 - ceaz
 - celuy
 - cestes
 - cestuy
 - chascune
 - chaüne
 - cinc
 - des
 - dez
 - douz
 - doze
 - iii
 - itels
 - le
 - lequel
 - lesquelles
 - lis
 - mez
 - mien
 - mondict
 - mout
 - mult
 - multes
 - negun
 - neuf
 - nos
 - nous
 - nuls
 - quantes
 - quele
 - quelles
 - quex
 - tels
 - trestote
 - trestutes
 - v
 - vij
 - xv
 - .iiij.m.
 - .vij.
 - .xix.
 - .xvij.
 - .xxxvi.m.
 - aucun
 - c
 - celes
 - cels
 - certaines
 - cette
 - chascuns
 - chinc
 - chis
 - cinquante
 - cis
 - dys
 - ices
 - icest
 - iceulx
 - ichele
 - icist
 - itele
 - itels
 - ix
 - la
 - ledit
 - lesdicts
 - lesdites
 - leur
 - liquel
 - liqueus
 - nulz
 - poi
 - quelque
 - seissante
 - soe
 - trestous
 - trestoute
 - trestouz
 - treze
 - troys
 - unes
 - vins
 - .iv.
 - .m.
 - .vi.
 - .viii.
 - .vj.
 - .xiiij.
 - .xij.
 - .xxv.
 - .xxv.m.
 - .xxx.
 - ·ssos
 - altres
 - ambesdous
 - ascune
 - aulcun
 - c
 - cela
 - cellui
 - certain
 - certains
 - chasque
 - chaüne
 - chaüns
 - che
 - cheün
 - cheün
 - chus
 - ciels
 - de
 - deux
 - diverse
 - dos
 - huna
 - ice
 - icist
 - il
 - ix
 - lesdictes
 - lesquelles
 - leurs
 - loi
 - los
 - mult
 - mulz
 - nesun
 - plusor
 - qel
 - quatorze
 - que
 - quinse
 - sadite
 # - sei #Confusion avec le plus courant <sei> pour <soi>
 - seisante
 - siet
 - soi
 - sondict
 - soun
 - tele
 - teux
 - tiel
 - tiele
 - tiex
 - totas
 - trente
 - tres
 - trestouz
 - trestute
 - tretoutes
 - u·
 - uit
 - unze
 - uuyt
 - vingtz
 - vinz
 - vos
 - vostres
 - xl
 - xvj
 - xxiiij
 - xxx
 - .cc.
 - .ccc.
 - .l.
 - .l.
 - .l.m.
 - .x _m_.
 - .xii.
 - .xiij.
 - .xvi.
 - .xviij.
 - .xx.
 - .xxiiii.
 - .xxiiij.
 - ·ls
 - alquantes
 - an.ii.
 - andeus
 - andex
 - ascun
 - aulcune
 - aulcuns
 - autres
 - autretele
 - cascune
 - celles
 - celui
 - centz
 - certaine
 - cescun
 - cestes
 - cesti
 - cet
 - chascuns
 - chele
 - chescune
 - ci
 - ciel
 - cilz
 - ciunc
 - divers
 - dose
 - dousze
 - huict
 - huit
 - huyt
 - ice
 - iceles
 - ices
 - icés
 - icez
 - icez
 - ichis
 - iiii
 - itel
 - lesquelx
 - mainz
 - molt
 - mondit
 - mout
 - noef
 - oit
 - onze
 - plusours
 - qual
 - quantes
 - quanz
 - quelle
 - quels
 - ques
 - saissante
 - seissante
 - seon
 - seze
 - so
 - soa
 - soen
 - sua
 - suen
 - t
 - teil
 - teuls
 - to
 - tos
 - trenta
 - trestot
 - trestoutes
 - tretout
 - tut
 - u
 - uint
 - votre
 - xij
 - xxi
 - xxviij
 - yceulx
 - .c.l.
 - .ccc.
 - .ccc.
 - .c iiij.
 - .ii.c.
 - .ii.m.
 - .iii.
 - .iii.c.
 - .iii.m.
 - .iiii.c.
 - .iiij. m.
 - .iij _m_.
 - .iij.m.
 - .ij _c_iiij.
 - .ixii.
 - .lij.
 - .lxij.m.
 - .lxx.
 - .lxxx.m.
 - .m.
 - .v.c.
 - .vi.
 - .vii.
 - .vii.xx.
 - .viii.
 - .viij.
 - .vij.c.
 - .x.m.
 - .xi.
 - .xi.
 - .xii. d.
 - .xiii.
 - .xiii.
 - .xl.
 - .xvii.
 - .xvii.
 - .xviii.
 - .xx.m.
 - .xxij.
 - .xxx m.
 - ·l
 - ·l
 - ·ll
 - ·nlo
 - ·sos
 - a
 - alcuns
 - alkun
 - alquant
 - alquante
 - altrë
 - altrien
 - am
 - ambdui
 - ambdui
 - ambedeus
 - ambes
 - ambesdouz
 - ambsdous
 - amedeus
 - amsdous
 - amsdous
 - an.ii.
 - anbedeus
 - anbedos
 - andeus
 - ansdous
 - anzdouz
 - aucunes
 - aukune
 - aulcunes
 - aulcung
 - autantes
 - autel
 - autele
 - autiex
 - autretel
 - autretex
 - autri
 - autrui
 - cascunes
 - cascunne
 - casscun
 - catre
 - ce
 - cel
 - celi
 - cels
 - celz
 - ceo
 - certaine
 - certein
 - certeins
 - certeinz
 - cescun
 - cest
 - ceuls
 - chacun
 - chasqu
 - cheles
 - chellui
 - chentisme
 - ches
 - chescuns
 - cheste
 - chestui
 - chist
 - ciel
 - ciel
 - ciest
 - cilla
 - cils
 - ciste
 - ciz
 - com
 - combien
 - cui
 - cui
 - deulx
 - dex
 - dez
 - diz
 - douse
 - douzse
 - dux
 - duze
 - duzze
 - en.ii.
 - guillames
 - huyct
 - i
 - iceaz
 - iceaz
 - icelles
 - icels
 - icelui
 - iceluy
 - iceo
 - icés
 - ichel
 - ichés
 - ichis
 - iciz
 - iiiixx
 - iiij.
 - iiije
 - ij
 - itant
 - itant
 - itantes
 - iteil
 - iteiz
 - iteuls
 - itex
 - itex
 - l
 - laquelle
 - las
 - lcel
 - lé
 - ledit
 - lers
 - lesdits
 - lesquelles
 - lesquelx
 - lesquelz
 - leurdit
 - li
 - lou
 - lou
 - lours
 - lxxvj
 - ly
 #- mains
    #La forme <mains> pour <maints> semble être bien minoritaire par rapport à son sens de MANUS.
 - maintz
 - mas
 - mé
 - meint
 - meintes
 - men
 - meu
 - mez
 - miens
 - millez
 - milz
 - mo
 - moie
 - mondict
 - mondit
 - mos
 - mutes
 - negune
 - neis
 - nent
 - nëul
 - nisun
 - nof
 - nostra
 - nostrae
 - nostre
 - notre
 - nu
 - nuesme
 - nuil
 - nuis
 - nul
 - oit
 - partot
 - pluiseurs
 - pluisors
 - pluisurs
 - plushurs
 - plusorz
 - plusur
 - qanz
 - qanz
 - qex
 - quans
 - quant
 - quant
 - quantez
 - quantez
 - quaranta
 - quarantë
 - quatr
 - quë
 - queiles
 - quelconque
 - quelconques
 - quelez
 - quelqu
 - quelx
 - queuls
 - queux
 - quiel
 - quilconques
 - quint
 - quinze
 - rien
 - san
 - sas
 - seisante
 - seize
 - sep
 - sesdiz
 - sessante
 - sesze
 - sexante
 - so·
 - soixante
 - som
 - sos
 - soun
 - su
 - sue
 - suens
 - suo
 - sus
 - tal
 - tals
 - tans
 - tant
 - tant
 - tas
 - teiz
 - teles
 - teles
 - tem
 - teon
 - terce
 - tielle
 - toi
 - tota
 - toutez
 - toutz
 - tox
 - trais
 - trante
 - trei
 - trent
 - trese
 - trestos
 - trestotes
 - trestout
 - trestut
 - trestutes
 - tretout
 - tretouz
 - tretuit
 - trium
 - troi
 - tua
 - tuiz
 - tus
 - u
 - una
 - unz
 - unze
 - uostre
 - uostres
 - uoz
 - vii
 - viii
 - viii
 - vin
 - vingts
 - vint
 - vns
 - vo
 - xii
 - xviij
 - xxj
 - xxv
 - xxvj
 - xxx
 - xxxix.
 - ycel
 - ycelles
 - ycellle
 - ycil
 - zzzl
