list:
 - qui
 - que
 - qu
 - qui
 - ki
 - ou
 - ki
 - cui
 - dont
 - que
 - don
 - u
 - ke
 - quanque
 - dunt
 - ou
 - qu
 - dunt
 - quanqu
 - quoi
 - coi
 - où
 - u
 - lequel
 - ke
 - quoy
 - dont
 - k
 - don
 - cui
 - dom
 - quei
 - c
 - quel
 - quë
 - quë
 - li
 - laquelle
 - q
 - quan
 - quanqu
 - dom
 - k
 - chi
 - quanque
 - quis
 - laquele
 - lo
 - quil
 - chi
 - kil
 - o
 - quex
 - unt
 - lesquelz
 - liquel
 - lesquelx
 - qoi
 - lesqueles
 - c
 - kis
 - les
 - dum
 - lesquelles
 - quae
 - ques
 - quant
 - dum
 - liquelx
 - lo
 - quels
 - qui
 - quiconques
 - les
 - li
 - qi
 - queus
 - kin
 - lequel
 - lesquels
 - lesqueus
 - liquels
 - liquels
 - quanques
 - quant
 - quantque
 - quiex
 - quil
 - auquel
 - dons
 - dun
 - dun
 - la
 - la
 - lezquelles
 - o
 - ont
 - qe
 - qes
 - qu
 - quai
 - quanz
 - queil
 - queiz
 - queles
 - queuls
 - quez
 - quis
 - ausquelz
 - ceo
 - chi
 - chil
 - ci
 - cu
 - delquel
 - dount
 - dount
 - dunc
 - duquel
 - iqui
 - kank
 - kanke
 - kanke
 - kel
 - kil
 - kis
 - kui
 - laquele
 - laquelle
 - laquelles
 - lequele
 - lesquex
 - lesquieulx
 - liqueus
 - loquel
 - on
 #- oui
 - porcoi
 - q
 - qanqu
 - qanque
 - qeus
 - qex
 - qi
 - qu
 - qu
 - qual
 - quals
 - quanc
 - quantcunque
 - quantqu
 - que
 - que
 - quei
 - queis
 - quele
 - quele
 - quelz
 - quen
 - quequ
 - queux
 - quez
 - qui
 - quikunques
 - quiqunke
 - quiqunkes
 - quit
 - quod
 - quoi
 - quoi
 - se
 - si
 - uqe
 - u
