list:
 - il
 - li
 - vos
 - s
 - l
 - le
 - se
 - je
 - me
 - ele
 - lui
 - m
 - vous
 - les
 - la
 #- moi
 - tu
 - ge
 - nos
 - il
 - nous
 - te
 - lor
 - vus
 - el
 - j
 - je
 #- luy
 - leur
 - nus
 - t
 - soi
 - voz
 - ilz
 - ele
 - jo
 - aus
 #- toi
 - lur
 - lo
 - vos
 - els
 - eles
 #- sei
 #- mei
 - elle
 - li
 - eus
 - jo
 #- moy
 - ax
 - s
 - ge
 - eulx
 - tu
 #- tei
 - jou
 - ils
 - jel
 - le
 - g
 - j
 - mi
 - se
 - i
 - l
 - nos
 - gel
 - gié
 - el
 - vous
 - noz
 - nus
 #- ·l
 - m
 - nous
 - euls
 - me
 - les
 #- soy
 - vus
 - uos
 - gel
 #- moi
 #- lié
 - g
 - elles
 - la
 - ce
 - jel
 - se
 - lez
 - eaux
 - ilz
 - voz
 - jeo
 #- toy
 - als
 - iaus
 - lui
 - elle
 - jol
 - lor
 - los
 - te
 - eulz
 - al
 - noz
 - eles
 - jou
 - t
 - elz
 - ii
 #- ·s
 - eaz
 - lour
 - lur
 #- ·ls
 #- ·m
 - eu
 - ges
 - jes
 #- loi
 - ous
 - eux
 - ges
 - iax
 - jes
 - lé
 #- lei
 - t
 #- tei
 #- ·il
 - c
 - ille
 - jeo
 - jol
 - l
 - nuns
 #- toi
 - vouz
 #- ·li
 - ex
 #- =-il
 - ils
 - lu
 - ti
 #- ·llor
 #- ·lo
 - auls
 - eaus
 - el
 - eu
 - gié
 - ill
 - jos
 - lë
 - lou
 - luy
 #- mei
 - nouz
 - que
 #- sei
 - vo
 - vouz
 #- ·lla'
 #- ·llo
 #- ·llos
 #- ·lz
 #- ·s'
 #- ·se
 #- ·ss'
 #- ·t
 #- ·tt'
 - a
 - al
 - alz
 - an
 - as
 - aus
 #- brait
 - ceo
 #- demande
 - dont
 - eaus
 - ela
 - ela
 - elë
 - elles
 - els
 - en
 - euz
 - gé
 - gë
 - ie
 - il
 - ille
 - jai
 - jë
 - jeol
 - jeu
 - joes
 - jon
 - jon
 - las
 - leur
 - leurs
 #- lié
 - lis
 - liu
 - lo
 #- m
 - no
 - nobis
 - nu
 - nul
 - ols
 - os
 - ouz
 #- s
 - sai
 - së
 - ses
 - te
 - té
 - un
 - vobis
 - vobis
 - vost
 - vostres
 - y
